// <auto-generated />
using System;
using ERP_Demo_Core_MVC.Models.DATABASEFOLDER;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Demo_Core_MVC.Migrations
{
    [DbContext(typeof(SchoolDB))]
    [Migration("20260220050434_school_wks")]
    partial class school_wks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_Demo_Core_MVC.Models.StudentModel", b =>
                {
                    b.Property<int>("Student_Roll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Roll"));

                    b.Property<int>("Student_Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Student_DOB")
                        .HasColumnType("date");

                    b.Property<string>("Student_Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_Roll");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
